name: HelloPlugin
version: 1.0
main: com.example.helloplugin.HelloPlugin
api-version: 1.20
commands:
  hello:
    description: 인사 명령어
  ping:
    description: 핑 확인
  goodbye:
    description: 작별 인사
  day:
    description: 오늘도 좋은 하루 보내세요.
